spring:
  application:
    name: FeignClientConsumer1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # you can give ip address also in default zone   http://10.0.0.191:8761/eureka
    register-with-eureka: true


server:
  port : 8081
